MOBILE-1140: In Bank selection screen show also those banks, which account linking is not supported
getkevin/kevin-ios pull request #60
Opened 2022-07-19 11:55 UTC by PocketDaniel

2022-07-20 06:25 UTC, edgar-zigis requested changes

2022-07-20 06:25 UTC, edgar-zigis commented on Sources/Kevin/Accounts/KevinAccountsConfiguration.swift
> +        private let showUnsupportedBanks: Bool
Builder should not have a constructor parameter with `showUnsupportedBanks` as only `callbackUrl` is mandatory. Provide this param in the builder instead like Android does [here](https://github.com/getkevin/kevin-android/pull/80/files). Default value for `showUnsupportedBanks` should be false.

2022-07-20 06:25 UTC, edgar-zigis commented on Sources/Kevin/Accounts/BankSelection/KevinBankSelectionConfiguration.swift
> +        showOnlyAccountLinkingSupportedBanks: Bool
I think we need to rename this to `excludeBanksWithoutAccountLinkingSupport`

2022-07-20 06:25 UTC, edgar-zigis commented on Sources/Kevin/Accounts/KevinAccountsPlugin.swift
> +    public func isShowUnsupportedBanks() throws -> Bool {
`shouldExcludeBanksWithoutAccountLinkingSupport()` and also change condition then

2022-07-20 06:43 UTC, typuk commented on Sources/Kevin/Accounts/LinkingSession/KevinAccountLinkingSession.swift
> +                    self.delegate?.onKevinAccountLinkingCanceled(error: error)
can omit self

2022-07-21 11:34 UTC, edgar-zigis approved these changes

2022-07-21 11:35 UTC, merged